;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (my de hypr idle)
  #:use-module (ice-9 match)
  #:use-module (gnu)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages wm)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (my core)
  #:use-module (my util features)
  #:use-module (my util defer)
  #:use-module (my util misc))

(define-record-type* <home-hypridle-configuration>
  home-hypridle-configuration make-home-hypridle-configuration
  home-hypridle-configuration?

  (package home-hypridle-configuration-package
           (default hypridle))

  (listeners home-hypridle-configuration-listeners
             (default '()))

  (lock-command home-hypridle-configuration-lock-command
                (default #f))

  (unlock-command home-hypridle-configuration-unlock-command
                  (default #f))

  (on-lock-command home-hypridle-configuration-on-lock-command
                   (default #f))

  (on-unlock-command home-hypridle-configuration-on-unlock-command
                     (default #f))

  (before-sleep-command home-hypridle-configuration-before-sleep-command
                        (default #f))

  (after-sleep-command home-hypridle-configuration-after-sleep-command
                       (default #f))
  
  (inhibit-sleep-mode home-hypridle-configuration-inhibit-sleep-mode
                      (default 2))
  
  (ignore-dbus-inhibit? home-hypridle-configuration-ignore-dbus-inhibit?
                        (default #f))

  (ignore-systemd-inhibit? home-hypridle-configuration-ignore-systemd-inhibit?
                           (default #f))

  (ignore-wayland-inhibit? home-hypridle-configuration-ignore-wayland-inhibit?
                           (default #f)))
(export home-hypridle-configuration)

(define-record-type* <hypridle-listener>
  hypridle-listener make-hypridle-listener
  hypridle-listener?

  (timeout hypridle-listener-timeout)

  (on-timeout-command hypridle-listener-on-timeout-command
                      (default #f))

  (on-resume-command hypridle-listener-on-resume-command
                     (default #f))

  (ignore-inhibit? hypridle-listener-ignore-inhibit?
                   (default #f)))
(export hypridle-listener)

(define hypridle-listener->string
  (match-lambda
    (($ <hypridle-listener>
        timeout on-timeout-command on-resume-command ignore-inhibit?)
     (string-append "listener {\n"
                    "  timeout = " (number->string timeout) "\n"
                    (maybe-wrap-string on-timeout-command "  on-timeout = " "\n")
                    (maybe-wrap-string on-resume-command "  on-resume = " "\n")
                    "  ignore_inhibit = " (boolean->yes-or-no ignore-inhibit?) "\n"
                    "}"))))

(define home-hypridle-configuration->file
  (match-lambda
    (($ <home-hypridle-configuration>
        _ listeners
        lock-command unlock-command
        on-lock-command on-unlock-command
        before-sleep-command after-sleep-command
        inhibit-sleep-mode ignore-dbus-inhibit?
        ignore-systemd-inhibit? ignore-wayland-inhibit?)
     (mixed-text-file "hypridle.conf"
                      "# Automatically generated by Arc's Guix config.\n\n"
                      "general {\n"
                      (maybe-wrap-string lock-command "  lock_cmd = " "\n")
                      (maybe-wrap-string unlock-command "  unlock_cmd = " "\n")
                      (maybe-wrap-string on-lock-command "  on_lock_cmd = " "\n")
                      (maybe-wrap-string on-unlock-command "  on_unlock_cmd = " "\n")
                      (maybe-wrap-string before-sleep-command "  before_sleep_cmd = " "\n")
                      (maybe-wrap-string before-sleep-command "  after_sleep_cmd = " "\n\n")
                      "  inhibit_sleep = " (number->string inhibit-sleep-mode) "\n"
                      "  ignore_dbus_inhibit = " (boolean->yes-or-no ignore-dbus-inhibit?) "\n"
                      "  ignore_systemd_inhibit = " (boolean->yes-or-no ignore-systemd-inhibit?) "\n"
                      "  ignore_wayland_inhibit = " (boolean->yes-or-no ignore-wayland-inhibit?) "\n"
                      "}\n\n"
                      (string-join (map hypridle-listener->string listeners) "\n\n")))))

(define (home-hypridle-shepherd-service config)
  (shepherd-service
   (documentation "Run Hypridle, Hyprland's idle management daemon.")
   (provision '(hypridle))
   (requirement '(graphical-session))
   
   (start #~(make-forkexec-constructor
             (list #$(string-append master-home-directory "/.dotfiles/guix/scripts/run-with-hypr-env")
                   #$(file-append (home-hypridle-configuration-package config)
                                  "/bin/hypridle"))
             #:environment-variables (cons* (string-append "WAYLAND_DISPLAY="
                                                           #$(or (getenv "WAYLAND_DISPLAY")
                                                                 "wayland-1"))
                                            (default-environment-variables))))
   
   (stop #~(make-kill-destructor))))

(define home-hypridle-service-type
  (service-type
   (name 'home-hypridle)
   (description "Home service to run and configure Hypridle, Hyprland's idle management daemon.")

   (default-value (home-hypridle-configuration))
   
   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list
                           (home-hypridle-configuration-package config))))

     (service-extension home-shepherd-service-type
                        (lambda (config)
                          (list
                           (home-hypridle-shepherd-service config))))
     
     (service-extension home-xdg-configuration-files-service-type
                        (lambda (config)
                          `(("hypr/hypridle.conf" ,(home-hypridle-configuration->file config)))))))))
(export home-hypridle-service-type)

(define listener-queue '())

(define-public (use-hypridle-listener listener)
  (set! listener-queue (cons listener listener-queue)))

(define-feature hypridle
  (defer
    (use-home-service
     (service home-hypridle-service-type
              (home-hypridle-configuration
               (listeners listener-queue))))))
