;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (arc suites media)
  #:use-module (ice-9 match)
  #:use-module (gnu)
  #:use-module (gnu services audio)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages mpd)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (arc core)
  #:use-module (arc util features)
  #:use-module (arc util codecs)
  #:use-module (arc util misc)
  #:use-module (arc system audio))

(define-record-type* <home-mpd-configuration>
  home-mpd-configuration make-home-mpd-configuration
  home-mpd-configuration?

  (package home-mpd-configuration-package
           (default mpd))
  
  (port home-mpd-configuration-port
        (default 6600))

  (outputs home-mpd-configuration-outputs
           (default '()))
  
  (music-directory home-mpd-configuration-music-directory
                   (default "~/Music"))

  (playlist-directory home-mpd-configuration-playlist-directory
                      (default "~/Music/Playlists"))
  
  (database-file home-mpd-configuration-database-file
                 (default "~/.local/share/mpd/database"))

  (state-file home-mpd-configuration-state-file
              (default "~/.local/share/mpd/state"))

  (sticker-file home-mpd-configuration-sticker-file
                (default "~/.local/share/mpd/sticker.sql"))

  (follow-symlinks? home-mpd-configuration-follow-symlinks?
                    (default #t))

  (auto-update? home-mpd-configuration-auto-update?
                (default #f)))
(export home-mpd-configuration)

(define (home-mpd-shepherd-service config)
  (shepherd-service
   (documentation "Run Music Player Daemon (MPD) under the current user.")
   (provision '(mpd))
   
   (start #~(make-forkexec-constructor
             (list #$(file-append (home-mpd-configuration-package config)
                                "/bin/mpd")
                   "--no-daemon")
             #:log-file (string-append (getenv "XDG_DATA_HOME") "/mpd/mpd.log")))
   
   (stop #~(make-kill-destructor))))

(define mpd-codec
  (let* ((kc basic-codec)
        (vc (make-chain-codec y-or-n-codec kc))
        (vc (make-wrapping-codec vc "\"" "\"\n")))
    (make-kv-codec kc vc)))

(define (simple-mpd-output->string output)
  (string-append "audio_output {\n"
                 (encode mpd-codec "\tname" (mpd-output-name output))
                 (encode mpd-codec "\ttype" (mpd-output-type output))
                 "}\n"))

(define write-home-mpd-configuration
  (match-lambda
    (($ <home-mpd-configuration>
        _ port outputs music-directory playlist-directory
        database-file state-file sticker-file
        follow-symlinks? auto-update?)
     (let ((c mpd-codec))
       (mixed-text-file "mpd.conf"
                        "# Automatically generated by Arc's Guix config.\n\n"
                        (encode c "port" port)
                        (encode c "music_directory" music-directory)
                        (encode c "playlist_directory" playlist-directory) "\n"
                        (encode c "db_file" database-file)
                        (encode c "state_file" state-file)
                        (encode c "sticker_file" sticker-file) "\n"
                        (encode c "follow_outside_symlinks" follow-symlinks?)
                        (encode c "follow_inside_symlinks" follow-symlinks?)
                        (encode c "auto_update" auto-update?) "\n"
                        
                        (string-join (map simple-mpd-output->string outputs) "\n"))))))

(define home-mpd-service-type
  (service-type
   (name 'home-mpd)
   (description "Home service to run Music Player Daemon (MPD) as the current user.")

   (default-value (home-mpd-configuration))
   
   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list
                           (home-mpd-configuration-package config))))

     (service-extension home-shepherd-service-type
                        (lambda (config)
                          (list
                           (home-mpd-shepherd-service config))))
     
     (service-extension home-xdg-configuration-files-service-type
                        (lambda (config)
                          `(("mpd/mpd.conf" ,(write-home-mpd-configuration config)))))))))
(export home-mpd-service-type)

(define-feature media
  (use-home-packages
   ;; Media Manipulation
   "ffmpeg"

   ;; Playback
   "mpv")

  (use-home-service
   (service home-mpd-service-type
            (home-mpd-configuration
             (outputs
              (list
               (mpd-output (name "Pipewire") (type "pipewire"))))
             (auto-update? #t)))))

