;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (arc system nix)
  #:use-module (srfi srfi-1)
  #:use-module (gnu)
  #:use-module (gnu services)
  #:use-module (gnu services nix)
  #:use-module (gnu home services)
  #:use-module (guix records)
  #:use-module (arc core)
  #:use-module (arc util features)
  #:use-module (arc util defer)
  #:use-module (arc system shells))


(define-record-type* <flake-input>
  flake-input make-flake-input
  flake-input?

  (name flake-input-name)
  (url flake-input-url))
(export flake-input)

;; NOTE: A flake generated by my config will directly reference these inputs.
;; If any of these aren't provided, the flake will probably break.

(define-public %base-flake-inputs
  (list (flake-input
         (name "nixpkgs")
         (url "github:nixos/nixpkgs/nixos-unstable"))
        
        (flake-input
         (name "flake-utils")
         (url "github:numtide/flake-utils"))
        
        (flake-input
         (name "flakey-profile")
         (url "github:lf-/flakey-profile"))))

;; TODO: Add support for declaring Nix package overlays from Guix.

;; FIXME: Nix's 'flakey-profile' recommends to pin flakes on a root level.
;; This fails because the entire '/etc/nix' directory is symlinked to the Guix store.
;; Pinning does work on a per-user level, though ideally it'd work with root too.

(define-record-type* <nix-flake>
  nix-flake make-nix-flake
  nix-flake?

  (inputs nix-flake-inputs
          (default %base-flake-inputs))

  (packages nix-flake-packages
            (default '())))
(export nix-flake)

(define (write-nix-flake flake)
  (mixed-text-file "flake.nix"
                   "{
  description = \"Flake generated by Guix.\";

  inputs = {\n" (string-concatenate (map (lambda (input)
                                           (string-pad (string-append (flake-input-name input)
                                                                      ".url = \""
                                                                      (flake-input-url input)
                                                                      "\";\n")
                                                       (+ (string-length (flake-input-name input))
                                                          (string-length (flake-input-url input))
                                                          15)))
                                         (nix-flake-inputs flake))) "  };

  outputs = { self, nixpkgs, flake-utils, flakey-profile, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = import nixpkgs { inherit system; config.allowUnfree = true; };
      in {
        packages.profile = flakey-profile.lib.mkProfile {
          inherit pkgs;

          pinned = { nixpkgs = toString nixpkgs; };
          paths = with pkgs; [\n" (string-concatenate (map (lambda (pkg)
                                                             (string-pad (string-append pkg "\n")
                                                                         (+ (string-length pkg) 13)))
                                                           (nix-flake-packages flake))) "          ];
        };
      });
}"))

(define-record-type* <home-flake-configuration>
  home-flake-configuration make-home-flake-configuration
  home-flake-configuration?

  (path home-flake-configuration-path)
  (flake home-flake-configuration-flake))
(export home-flake-configuration)

(define-public home-flake-service-type
  (service-type
   (name 'home-flake)
   (description "Home service to generate a Nix flake.")

   (extensions
    (list
     (service-extension home-activation-service-type
                        (lambda (config)
                          #~(begin
                              (let ((dest (string-append (getenv "HOME")
                                                         "/"
                                                         #$(home-flake-configuration-path config))))
                                (mkdir-p (dirname dest))
                                
                                (when (file-exists? dest)
                                  (delete-file dest))
                                 
                                (copy-file #$(write-nix-flake (home-flake-configuration-flake config))
                                           dest)))))
     
     (service-extension home-environment-variables-service-type
                        (lambda (config)
                          (list (cons "PATH" "$HOME/.nix-profile/bin:$PATH"))))))

   (compose concatenate)

   ;; TODO: Allow extensions to specify new flake inputs.
   
   (extend
    (lambda (config packages)
      (let ((flake (home-flake-configuration-flake config)))
        (home-flake-configuration
         (inherit config)
         (flake (nix-flake
                 (inherit flake)
                 (packages (append (nix-flake-packages flake)
                                   packages))))))))))

(define used-nix-packages '())

(define* (use-nix-packages #:rest packages)
  (set! used-nix-packages (append used-nix-packages packages)))
(export use-nix-packages)

(define-feature nix
  (use-nix-packages "nh")
  
  (use-service
   (service nix-service-type
            (nix-configuration
             (extra-config
              (list "experimental-features = nix-command flakes")))))
  
  (defer
    (use-home-service
     (service home-flake-service-type
              (home-flake-configuration
               (path ".dotfiles/guix/gen/nix/flake.nix")
               (flake (nix-flake
                       (packages used-nix-packages))))))))
