;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (my apps editors emacs)
  #:use-module (gnu)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages emacs)
  #:use-module (gnu home)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (my core)
  #:use-module (my theming)
  #:use-module (my util features)
  #:use-module (my system shells))

(define-record-type* <home-emacs-configuration>
  home-emacs-configuration make-home-emacs-configuration
  home-emacs-configuration?

  (package home-emacs-configuration-package
           (default emacs))

  (daemon? home-emacs-configuration-daemon?
           (default #f)))

(define (home-emacs-shepherd-service config)
  (shepherd-service
   (documentation "Run Emacs, the hackable text editor, as a daemon.")
   (provision '(emacs))

   (start #~(make-forkexec-constructor
             (list #$(file-append (home-emacs-configuration-package config)
                                  "/bin/emacs")
                   "--fg-daemon")))

   (stop #~(make-kill-destructor))))

(define (write-home-emacs-theme)
  (cons ".dotfiles/guix/gen/emacs-guix-theme.el"
        (mixed-text-file "emacs-guix-theme.el"
                         ";;; emacs-guix-theme   -*- lexical-binding: t; -*-

;; Author: Guix <AUTO>
;; Keywords: theme
;; Version: 0.0.1

;;; Commentary:

;; This package provides a theme automatically generated by Arc's Guix configuration.

;;; Code:
(require 'base16-theme)

(defvar emacs-guix-theme-colors
  '(:base00 \"" (color->hex (get-color 'base00)) "\"
    :base01 \"" (color->hex (get-color 'base01)) "\"
    :base02 \"" (color->hex (get-color 'base02)) "\"
    :base03 \"" (color->hex (get-color 'base03)) "\"
    :base04 \"" (color->hex (get-color 'base04)) "\"
    :base05 \"" (color->hex (get-color 'base05)) "\"
    :base06 \"" (color->hex (get-color 'base06)) "\"
    :base07 \"" (color->hex (get-color 'base07)) "\"
    :base08 \"" (color->hex (get-color 'base08)) "\"
    :base09 \"" (color->hex (get-color 'base09)) "\"
    :base0A \"" (color->hex (get-color 'base0A)) "\"
    :base0B \"" (color->hex (get-color 'base0B)) "\"
    :base0C \"" (color->hex (get-color 'base0C)) "\"
    :base0D \"" (color->hex (get-color 'base0D)) "\"
    :base0E \"" (color->hex (get-color 'base0E)) "\"
    :base0F \"" (color->hex (get-color 'base0F)) "\")
  \"All the colors for Guix's Emacs theme.\")

(deftheme emacs-guix)

(base16-theme-define 'emacs-guix emacs-guix-theme-colors)

(provide-theme 'emacs-guix)

(add-to-list 'custom-theme-load-path (file-truename \"~/.dotfiles/guix/gen/\"))

(provide 'emacs-guix-theme)
;;; emacs-guix-theme.el ends here
")))

(define home-emacs-service-type
  (service-type
   (name 'home-emacs)
   (description "Home service to install Emacs, and possibly set up its daemon.")

   (default-value (home-emacs-configuration))
   
   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list
                           (home-emacs-configuration-package config))))

     (service-extension home-shepherd-service-type
                        (lambda (config)
                          (if (home-emacs-configuration-daemon? config)
                              (list
                               (home-emacs-shepherd-service config))
                              '())))

     (service-extension home-theming-service-type
                        (lambda (_)
                          (list
                           (theming-target
                            (provision '(emacs))
                            (file write-home-emacs-theme)))))))))
(export home-emacs-service-type)

(define-feature emacs
  (use-home-service
   (service home-emacs-service-type
            (home-emacs-configuration
             (package emacs-pgtk)
             (daemon? #t))))

  (provide-shell-alias "emacs" "emacsclient -c"))
