(define-module (my suites media)
  #:use-module (ice-9 match)
  #:use-module (gnu)
  #:use-module (gnu services audio)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages mpd)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (my core)
  #:use-module (my utils units)
  #:use-module (my utils misc)
  #:use-module (my system audio))

(define-record-type* <home-mpd-configuration>
  home-mpd-configuration make-home-mpd-configuration
  home-mpd-configuration?

  (package home-mpd-configuration-package
           (default mpd))
  
  (port home-mpd-configuration-port
        (default 6600))

  (outputs home-mpd-configuration-outputs
           (default '()))
  
  (music-directory home-mpd-configuration-music-directory
                   (default "~/Music"))

  (playlist-directory home-mpd-configuration-playlist-directory
                      (default "~/Music/Playlists"))
  
  (database-file home-mpd-configuration-database-file
                 (default "~/.local/share/mpd/database"))

  (state-file home-mpd-configuration-state-file
              (default "~/.local/share/mpd/state"))

  (sticker-file home-mpd-configuration-sticker-file
                (default "~/.local/share/mpd/sticker.sql"))

  (follow-symlinks? home-mpd-configuration-follow-symlinks?
                    (default #t))

  (auto-update? home-mpd-configuration-auto-update?
                (default #f)))
(export home-mpd-configuration)

(define (home-mpd-shepherd-service config)
  (shepherd-service
   (documentation "Music Player Daemon (MPD)")
   (provision '(mpd))
   (start #~(make-forkexec-constructor
             (list #$(file-append (home-mpd-configuration-package config)
                                "/bin/mpd")
                   "--no-daemon")
             #:log-file (string-append (getenv "XDG_DATA_HOME") "/mpd/mpd.log")))
   (stop #~(make-kill-destructor))))

(define (simple-mpd-output->string output)
  (format #f "audio_output {\n\tname \"~a\"\n\ttype \"~a\"\n}\n"
          (mpd-output-name output)
          (mpd-output-type output)))

(define write-home-mpd-configuration
  (match-lambda
    (($ <home-mpd-configuration>
        _ port outputs music-directory playlist-directory
        database-file state-file sticker-file
        follow-symlinks? auto-update?)
     (mixed-text-file "mpd.conf"
                      "# Automatically generated by Arc's Guix config.\n\n"
                      "port \"" (number->string port) "\"\n\n"
                      "music_directory \"" music-directory "\"\n"
                      "playlist_directory \"" playlist-directory "\"\n\n"
                      "db_file \"" database-file "\"\n"
                      "state_file \"" state-file "\"\n"
                      "sticker_file \"" sticker-file "\"\n\n"
                      "follow_outside_symlinks \"" (boolean->yes-or-no follow-symlinks?) "\"\n"
                      "follow_inside_symlinks \"" (boolean->yes-or-no follow-symlinks?) "\"\n"
                      "auto_update \"" (boolean->yes-or-no auto-update?) "\"\n\n"
                      (string-join (map simple-mpd-output->string outputs) "\n")))))

(define home-mpd-service-type
  (service-type
   (name 'home-mpd)
   (description "Home service to run Music Player Daemon (MPD) as the current user.")

   (default-value (home-mpd-configuration))
   
   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list
                           (home-mpd-configuration-package config))))

     (service-extension home-shepherd-service-type
                        (lambda (config)
                          (list
                           (home-mpd-shepherd-service config))))
     
     (service-extension home-xdg-configuration-files-service-type
                        (lambda (config)
                          `(("mpd/mpd.conf" ,(write-home-mpd-configuration config)))))))))
(export home-mpd-service-type)

(define-unit ((suites media))
  (use-home-packages
   ;; Media Manipulation
   "ffmpeg"

   ;; Downloaders
   "yt-dlp"
   "ani-cli"

   ;; Playback
   "mpv")

  (use-home-service
   (service home-mpd-service-type
            (home-mpd-configuration
             (outputs
              (list
               (mpd-output (name "Pipewire") (type "pipewire"))))
             (auto-update? #t)))))

(hook-unit '(suites media) '(system audio))
