;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (arc de hypr idle)
  #:use-module (gnu)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages window-management)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (arc core)
  #:use-module (arc util features)
  #:use-module (arc util codecs)
  #:use-module (arc util defer)
  #:use-module (arc util misc)
  #:use-module (arc de hypr codecs))

;; TODO: Move this to a dedicated module for screen lockers.

(define-public system-lock-command #f)

(define-record-type* <home-hypridle-configuration>
  home-hypridle-configuration make-home-hypridle-configuration
  home-hypridle-configuration?

  (package home-hypridle-configuration-package
           (default hypridle))

  (listeners home-hypridle-configuration-listeners
             (default '()))

  (lock-command home-hypridle-configuration-lock-command
                (default #f))

  (unlock-command home-hypridle-configuration-unlock-command
                  (default #f))

  (on-lock-command home-hypridle-configuration-on-lock-command
                   (default #f))

  (on-unlock-command home-hypridle-configuration-on-unlock-command
                     (default #f))

  (before-sleep-command home-hypridle-configuration-before-sleep-command
                        (default #f))

  (after-sleep-command home-hypridle-configuration-after-sleep-command
                       (default #f))
  
  (inhibit-sleep-mode home-hypridle-configuration-inhibit-sleep-mode
                      (default 2))
  
  (ignore-dbus-inhibit? home-hypridle-configuration-ignore-dbus-inhibit?
                        (default #f))

  (ignore-systemd-inhibit? home-hypridle-configuration-ignore-systemd-inhibit?
                           (default #f))

  (ignore-wayland-inhibit? home-hypridle-configuration-ignore-wayland-inhibit?
                           (default #f)))
(export home-hypridle-configuration)

(define-record-type* <hypridle-listener>
  hypridle-listener make-hypridle-listener
  hypridle-listener?

  (timeout hypridle-listener-timeout)

  (on-timeout-command hypridle-listener-on-timeout-command
                      (default #f))

  (on-resume-command hypridle-listener-on-resume-command
                     (default #f))

  (ignore-inhibit? hypridle-listener-ignore-inhibit?
                   (default #f)))
(export hypridle-listener)

(define-matcher (hypridle-listener->string listener)
  (($ <hypridle-listener>
      timeout on-timeout-command on-resume-command ignore-inhibit?)
   (let* ((c hyprlang-codec)
          (m (make-cond-codec c)))
     (string-append "listener {\n"
                    (with-space-indent 2 "\n"
                      (encode c "timeout" timeout)
                      (encode m "on-timeout" on-timeout-command)
                      (encode m "on-resume" on-resume-command)
                      (encode c "ignore_inhibit" ignore-inhibit?))
                    "\n}"))))

(define-matcher (home-hypridle-configuration->file config)
  (($ <home-hypridle-configuration>
      _ listeners
      lock-command unlock-command
      on-lock-command on-unlock-command
      before-sleep-command after-sleep-command
      inhibit-sleep-mode ignore-dbus-inhibit?
      ignore-systemd-inhibit? ignore-wayland-inhibit?)
   (let* ((c hyprlang-codec)
          (m (make-cond-codec c)))
     (mixed-text-file "hypridle.conf"
                      "# Automatically generated by Arc's Guix config.\n\n"
                      "general {\n"
                      (with-space-indent 2 "\n"
                        (encode m "lock_cmd" lock-command)
                        (encode m "unlock_cmd" unlock-command)
                        (encode m "on_lock_cmd" on-lock-command)
                        (encode m "on_unlock_cmd" on-unlock-command)
                        (encode m "before_sleep_cmd" before-sleep-command)
                        (encode m "after_sleep_cmd" after-sleep-command)

                        (encode c "inhibit_sleep" inhibit-sleep-mode)
                        (encode c "ignore_dbus_inhibit" ignore-dbus-inhibit?)
                        (encode c "ignore_systemd_inhibit" ignore-systemd-inhibit?)
                        (encode c "ignore_wayland_inhibit" ignore-wayland-inhibit?))
                      "\n}\n\n"
                      
                      (string-join (map hypridle-listener->string listeners) "\n\n")))))

(define (home-hypridle-shepherd-service config)
  (shepherd-service
   (documentation "Run Hypridle, Hyprland's idle management daemon.")
   (provision '(hypridle))
   (requirement '(graphical-session))
   
   (start #~(make-forkexec-constructor
             (list #$(string-append master-home-directory "/.dotfiles/guix/scripts/run-with-hypr-env")
                   #$(file-append (home-hypridle-configuration-package config)
                                  "/bin/hypridle"))
             #:environment-variables (cons* (string-append "WAYLAND_DISPLAY="
                                                           #$(or (getenv "WAYLAND_DISPLAY")
                                                                 "wayland-1"))
                                            (default-environment-variables))))
   
   (stop #~(make-kill-destructor))))

(define home-hypridle-service-type
  (service-type
   (name 'home-hypridle)
   (description "Home service to run and configure Hypridle, Hyprland's idle management daemon.")

   (default-value (home-hypridle-configuration))
   
   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list
                           (home-hypridle-configuration-package config))))

     (service-extension home-shepherd-service-type
                        (lambda (config)
                          (list
                           (home-hypridle-shepherd-service config))))
     
     (service-extension home-xdg-configuration-files-service-type
                        (lambda (config)
                          `(("hypr/hypridle.conf" ,(home-hypridle-configuration->file config)))))))))
(export home-hypridle-service-type)

(define listener-queue '())

(define-public (use-hypridle-listener listener)
  (push! listener-queue listener))

(define-feature hypridle
  (defer
    (use-home-service
     (service home-hypridle-service-type
              (home-hypridle-configuration
               (listeners listener-queue)
               (lock-command system-lock-command))))))
