#!/bin/sh
# Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
#
# This file is NOT part of GNU Guix.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build the package, saving its path that's inside '/gnu/store/'.
store_path="$(guix build $@)"

if [[ -z "$store_path" ]]; then
    echo "Error: Package failed to build, or it has no outputs!" >&2
    exit 1
fi

# FIXME: If the built package has multiple store paths, the symlink will be invalid.
# This is because my script assumes the build command will only return one path.
# Instead though, it can also return a list of paths seperated by newlines.

# Create a symlink, in the current directory, that points to this package.
ln -s "$store_path" "result"
