#!/bin/sh
# Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
#
# This file is NOT part of GNU Guix.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

output=$1

if [ -z $output ]; then
    echo "Error: Output file not specified" >&2
    exit 1
fi

cwd=$(pwd)
cd ~/.dotfiles/guix

image=$(guix system image --image-type=iso9660 installer.scm)
status=$?

cd $cwd

if [ $status -ne 0 ]; then
    echo "Error: Failed to build installer image" >&2
    exit 2
fi

ln -sf $image $output
