#!/bin/sh
# Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
#
# This file is NOT part of GNU Guix.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script runs a provided command, ensuring it has access to environment variables set by Hyprland.
# This is useful for things like Shepherd services, which are ran within a sandboxed environment.

# TODO: Find a working way to get the ID of the user running Hyprland.

# HACK: Yes, hardcoding the UID here is extremely stupid.
# For some reason, the UID environment variable doesn't work for home Shepherd services.
# This is basically a band-aid fix that should be replaced soon.

hypr_dir="/run/user/1000/hypr"

if [ ! -d "$hypr_dir" ]; then
    echo "Error: Failed to find Hyprland socket directory" >&2
    exit 1
fi

# This tries to find the last-modified Hyprland socket.
socket=$(find "$hypr_dir" -maxdepth 1 -type d -printf '%T@ %f\n' 2>/dev/null \
    | tail -n +2 \
    | sort -rn \
    | head -1 \
    | cut -d ' ' -f 2-)

if [ -z "$socket" ]; then
    echo "Error: Hyprland socket directory is empty" >&2
    exit 2
fi

export HYPRLAND_INSTANCE_SIGNATURE="$socket"

# Run the provided command with all arguments.
# This replaces the current process.
exec $@
