;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (arc de hypr)
  #:use-module (ice-9 match)
  #:use-module (gnu)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages wm)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu home)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (guix records)
  #:use-module (arc core)
  #:use-module (arc theming)
  #:use-module (arc util features)
  #:use-module (arc util keys)
  #:use-module (arc util codecs)
  #:use-module (arc util defer)
  #:use-module (arc util misc)
  #:use-module (arc system graphics)
  #:use-module (arc de hypr codecs)
  #:use-module (arc de hypr dispatch)
  #:use-module (arc de wallpaper))

;; TODO: Allow specifying Hyprland's keybind flags from Scheme.

(define (hypr-keybind->string bind-and-dispatcher)
  (let ((vc hypr-value-codec))
    (string-append "hl.bind("
                   (encode vc (car bind-and-dispatcher))
                   ", "
                   (expand-hypr-dispatcher (cdr bind-and-dispatcher))
                   ")")))

;; TODO: Add additional monitor fields as needed.

(define-record-type* <hypr-monitor>
  hypr-monitor make-hypr-monitor
  hypr-monitor?

  (output hypr-monitor-output
          (default #f))

  (resolution hypr-monitor-resolution
              (default 'preferred))

  (refresh-rate hypr-monitor-refresh-rate
                (default #f))

  (position hypr-monitor-position
            (default 'auto))

  (scale hypr-monitor-scale
         (default 1)))
(export hypr-monitor
        hypr-monitor?
        hypr-monitor-output
        hypr-monitor-resolution
        hypr-monitor-refresh-rate
        hypr-monitor-position
        hypr-monitor-scale)

(define-public (hypr-monitor-mode monitor)
  (let ((vc hypr-value-codec)
        (rc resolution-codec)
        (res (hypr-monitor-resolution monitor))
        (rate (hypr-monitor-refresh-rate monitor)))
    (if (symbol? res)
        (encode vc res)
        (string-append (encode rc res)
                       (if rate "@" "")
                       (if rate (encode vc rate) "")))))

(define-matcher (hypr-monitor->encodable monitor)
  (($ <hypr-monitor>
      output _ _ position scale)
   `((output . ,(or output ""))
     (mode . ,(hypr-monitor-mode monitor))
     (position . ,(if (symbol? position)
                      (symbol->string position)
                      position))
     (scale . ,scale))))

;; TODO: Add support for Hyprland's window rules, animations, and more.
;; TODO: Allow specifying dispatchers to run when Hyprland starts.

(define-record-type* <home-hyprland-configuration>
  home-hyprland-configuration make-home-hyprland-configuration
  home-hyprland-configuration?

  (package home-hyprland-configuration-package
           (default hyprland))
  
  (monitors home-hyprland-configuration-monitors
            (default '()))

  (keybinds home-hyprland-configuration-keybinds
            (default '()))

  (option-sets home-hyprland-configuration-option-sets
               (default '())))
(export home-hyprland-configuration
        home-hyprland-configuration?
        home-hyprland-configuration-package
        home-hyprland-configuration-monitors
        home-hyprland-configuration-keybinds
        home-hyprland-configuration-option-sets)

(define (home-hyprland-configuration->file config)
  (let ((vc hypr-value-codec)
        (cc hypr-call-codec))
    (mixed-text-file "hyprland.lua"
                     (as-joined-string "\n"
                       "-- Automatically generated by Arc's Guix config."
                       "\n--- Monitors"
                       (string-join
                        (map (lambda (mon)
                               (encode cc
                                       'hl.monitor
                                       (list (hypr-monitor->encodable mon))))
                             (home-hyprland-configuration-monitors config))
                        "\n")
                       "\n--- Keybinds"
                       (string-join
                        (map hypr-keybind->string
                             (home-hyprland-configuration-keybinds config))
                        "\n")
                       "\n--- Options"
                       (string-join
                        (map (lambda (opts) (encode cc 'hl.config (list opts)))
                             (home-hyprland-configuration-option-sets config))
                        "\n")))))

(define-public home-hyprland-service-type
  (service-type
   (name 'home-hyprland)
   (description "Home service to generate a Lua configuration for Hyprland.")

   (default-value (home-hyprland-configuration))

   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (config)
                          (list (home-hyprland-configuration-package config))))

     (service-extension home-xdg-configuration-files-service-type
                        (lambda (config)
                          `(("hypr/hyprland.lua" ,(home-hyprland-configuration->file config)))))))))
(export home-hyprland-service-type)

;; FIXME: Hyprpaper is completely broken on my system; I'll investigate this later.

(define home-hyprpaper-shepherd-service
  (shepherd-service
   (documentation "Run Hyprpaper, Hyprland's wallpaper daemon.")
   (provision '(hyprpaper))
   (requirement '(graphical-session))

   (start #~(make-forkexec-constructor
             (list #$(file-append hyprpaper "/bin/hyprpaper"))
             #:environment-variables (cons* (string-append "WAYLAND_DISPLAY="
                                                           #$(or (getenv "WAYLAND_DISPLAY")
                                                                 "wayland-1"))
                                            (default-environment-variables))))

   (stop #~(make-kill-destructor))))

(define (write-home-hyprpaper-configuration)
  (cons ".config/hypr/hyprpaper.conf"
        (mixed-text-file "hyprpaper.conf"
                         "# Automatically generated by Arc's Guix config.

wallpaper {
  monitor =
  path = " (theme-wallpaper (current-theme)) "
  fit_mode = cover
}")))

(define-public home-hyprpaper-service-type
  (service-type
   (name 'home-hyprpaper)
   (description "Home service for running and configuring Hyprpaper, Hyprland's wallpaper daemon.")

   (default-value '())

   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (_)
                          (list hyprpaper)))

     (service-extension home-shepherd-service-type
                        (lambda (_)
                          (list home-hyprpaper-shepherd-service)))

     (service-extension home-theming-service-type
                        (lambda (_)
                          (list
                           (theming-target
                            (provision '(hyprpaper))
                            (file write-home-hyprpaper-configuration)))))))))

(define *hypr-monitors* '())
(define *hypr-keybinds* '())
(define *hypr-option-sets* '())

(define-public (use-hypr-monitor monitor)
  (push! *hypr-monitors* monitor))

(define-public (bind-hypr bind dispatcher)
  (push! *hypr-keybinds* (cons bind dispatcher)))

(define-public (use-hypr-options set)
  (push! *hypr-option-sets* set))

(define-feature hyprland
  (feat-require 'wayland)
  
  (use-home-service (service home-swww-service-type))

  (defer
    (use-home-service
     (service home-hyprland-service-type
              (home-hyprland-configuration
               (monitors (reverse *hypr-monitors*))
               (keybinds (reverse *hypr-keybinds*))
               (option-sets (reverse *hypr-option-sets*)))))))
