;;; Copyright © 2025-2026 Arcensyl <dev@arcensyl.me>
;;;
;;; This file is NOT part of GNU Guix.
;;;
;;; This program is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the Free
;;; Software Foundation; either version 3 of the License, or (at your option)
;;; any later version.
;;;
;;; This program is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
;;; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;;; for more details.
;;;
;;; You should have received a copy of the GNU General Public License along
;;; with this program.  If not, see <http://www.gnu.org/licenses/>.

(define-module (arc de hypr)
  #:use-module (gnu)
  #:use-module (gnu services shepherd)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu home)
  #:use-module (gnu home services)
  #:use-module (gnu home services shepherd)
  #:use-module (arc core)
  #:use-module (arc theming)
  #:use-module (arc util features)
  #:use-module (arc util codecs)
  #:use-module (arc system graphics)
  #:use-module (arc de wallpaper))

;; TODO: Write a custom home service for configuring Hyprland.

(define-public hypr-codec
  (let ((c (make-chain-codec y-or-n-codec basic-codec)))
    (make-kv-codec c #f " = ")))

;; FIXME: Hyprpaper is completely broken on my system; I'll investigate this later.

(define home-hyprpaper-shepherd-service
  (shepherd-service
   (documentation "Run Hyprpaper, Hyprland's wallpaper daemon.")
   (provision '(hyprpaper))
   (requirement '(graphical-session))

   (start #~(make-forkexec-constructor
             (list #$(file-append hyprpaper "/bin/hyprpaper"))
             #:environment-variables (cons* (string-append "WAYLAND_DISPLAY="
                                                           #$(or (getenv "WAYLAND_DISPLAY")
                                                                 "wayland-1"))
                                            (default-environment-variables))))

   (stop #~(make-kill-destructor))))

(define (write-home-hyprpaper-configuration)
  (cons ".config/hypr/hyprpaper.conf"
        (mixed-text-file "hyprpaper.conf"
                         "# Automatically generated by Arc's Guix config.

wallpaper {
  monitor =
  path = " (theme-wallpaper (current-theme)) "
  fit_mode = cover
}")))

(define-public home-hyprpaper-service-type
  (service-type
   (name 'home-hyprpaper)
   (description "Home service for running and configuring Hyprpaper, Hyprland's wallpaper daemon.")

   (default-value '())

   (extensions
    (list
     (service-extension home-profile-service-type
                        (lambda (_)
                          (list hyprpaper)))

     (service-extension home-shepherd-service-type
                        (lambda (_)
                          (list home-hyprpaper-shepherd-service)))

     (service-extension home-theming-service-type
                        (lambda (_)
                          (list
                           (theming-target
                            (provision '(hyprpaper))
                            (file write-home-hyprpaper-configuration)))))))))

(define-feature hyprland
  (feat-require 'wayland)
  
  (use-home-packages "hyprland")
  (use-home-service (service home-swww-service-type)))
